[platformio]
default_envs = esp32dev

[env]
platform = platformio/espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
lib_deps =
  knolleary/PubSubClient@^2.8

[env:esp32dev]

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = orvibo_esp32_blinds.local

[env:capture]
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
  -DRF_CAPTURE_MODE=1
