[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=3
lib_deps =
  knolleary/PubSubClient@^2.8
