from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path

from aok_protocol import load_remote_config, raw_list_for_action, timings_from_config


def cpp_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"blind_{cleaned}"
    return cleaned.lower()


def cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def pulse_array(values: list[int], indent: str = "  ") -> str:
    lines: list[str] = []
    current: list[str] = []
    length = 0
    for value in values:
        text = str(abs(value))
        if current and length + len(text) + 2 > 96:
            lines.append(indent + ", ".join(current) + ",")
            current = []
            length = 0
        current.append(text)
        length += len(text) + 2
    if current:
        lines.append(indent + ", ".join(current))
    return "\n".join(lines)


def command_array(remote: dict[str, object], channels: list[int], action: str) -> tuple[list[int], int, int]:
    raw = raw_list_for_action(remote, channels, action)
    timings = timings_from_config(remote)
    if raw and raw[-1] < 0 and abs(raw[-1]) >= 3000:
        raw = raw[:-1]
    gap_ms = max(1, int(math.ceil(timings.gap / 1000)))
    return [abs(value) for value in raw], timings.repeats, gap_ms


def resolve_remote_path(remote_value: str, blinds_path: Path) -> Path:
    remote_path = Path(remote_value)
    if remote_path.is_absolute():
        return remote_path
    candidate = blinds_path.parent / remote_path
    if candidate.exists():
        return candidate
    return remote_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate include/blinds.local.h from AOK calibration and blind/channel mapping.")
    parser.add_argument("--remote", type=Path, required=True, help="data/remote_calibration.json")
    parser.add_argument("--blinds", type=Path, required=True, help="data/blinds.json")
    parser.add_argument("--out", type=Path, default=Path("include/blinds.local.h"))
    args = parser.parse_args()

    default_remote = load_remote_config(args.remote)
    remote_cache: dict[str, dict[str, object]] = {str(args.remote): default_remote}
    blinds = json.loads(args.blinds.read_text(encoding="utf-8"))

    output: list[str] = [
        "#pragma once",
        "",
        "#include \"blind_types.h\"",
        "",
        "// Generated by tools/generate_blinds_local.py.",
        "// Regenerate after changing data/blinds.json or any remote calibration JSON.",
        "",
    ]

    definitions: list[str] = []
    for blind in blinds:
        blind_id = cpp_id(str(blind["id"]))
        channels = [int(channel) for channel in blind["channels"]]
        if "remote" in blind:
            remote_path = resolve_remote_path(str(blind["remote"]), args.blinds)
            remote_key = str(remote_path)
            if remote_key not in remote_cache:
                remote_cache[remote_key] = load_remote_config(remote_path)
            remote = remote_cache[remote_key]
        else:
            remote = default_remote
        for action in ("open", "close", "stop"):
            pulses, repeats, gap_ms = command_array(remote, channels, action)
            array_name = f"{blind_id}_{action}_pulses"
            output.append(f"static const uint16_t {array_name}[] = {{")
            output.append(pulse_array(pulses))
            output.append("};")
            output.append("")
            blind[f"_{action}_array"] = array_name
            blind[f"_{action}_count"] = len(pulses)
            blind[f"_{action}_repeats"] = repeats
            blind[f"_{action}_gap_ms"] = gap_ms

    output.append("static const BlindDefinition BLINDS[] = {")
    for blind in blinds:
        blind_id = cpp_id(str(blind["id"]))
        name = cpp_string(str(blind["name"]))
        full_travel_ms = int(blind.get("full_travel_ms", 30000))
        initial_position = int(blind.get("initial_position", -1))
        invert_position = "true" if bool(blind.get("invert_position", False)) else "false"
        output.extend(
            [
                "  {",
                f"    \"{blind_id}\",",
                f"    \"{name}\",",
                f"    {full_travel_ms},",
                f"    {initial_position},",
                f"    {invert_position},",
                f"    RawRfCommand{{\"open\", {blind['_open_array']}, {blind['_open_count']}, {blind['_open_repeats']}, {blind['_open_gap_ms']}}},",
                f"    RawRfCommand{{\"close\", {blind['_close_array']}, {blind['_close_count']}, {blind['_close_repeats']}, {blind['_close_gap_ms']}}},",
                f"    RawRfCommand{{\"stop\", {blind['_stop_array']}, {blind['_stop_count']}, {blind['_stop_repeats']}, {blind['_stop_gap_ms']}}},",
                "  },",
            ]
        )
    output.append("};")
    output.append("")
    output.append("static constexpr size_t BLIND_COUNT = sizeof(BLINDS) / sizeof(BLINDS[0]);")
    output.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(output), encoding="utf-8")
    print(f"Wrote {args.out}")
    print(f"Generated {len(blinds)} blind definitions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
